name: CI/CD for HR Attrition App

on:
  push:
    branches: [ "main" ]   # Runs whenever code is pushed to main branch
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest   # You can skip this if you don’t have tests

  deploy:
    runs-on: ubuntu-latest
    needs: build   # Only run if build succeeds

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: "hr-attrition-app"   # Your Azure App Service name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .

